pkg/logstructured/logstructured.go
If we list and get no rows back we also don't know the current revision
because of how the queries are structured. In that situation we get the
current revision and then re-list to ensure we don't miss anything.
=> Make revision consistent for empty sets

pkg/logstructured/logstructured.go
https://github.com/rancher/k3s/issues/1628
=> Add mutex to event ttl

pkg/drivers/mysql/mysql.go, pkg/drivers/pgsql/pgsql.go
https://github.com/rancher/k3s/issues/1392
=> add name id index to mysql and postgres

.drone.yml, .golangci.json, Dockerfile.dapper, pkg/logstructured/logstructured.go, scripts/build, scripts/ci, scripts/entry, scripts/package, scripts/test, scripts/validate, scripts/validate-ci, scripts/version
I really needed those public docker images, so I've copied all the scripst over from the project referenced by @ibuildthecloud in #26.
I've got no experience with dapper/drone so hopefully it just works. Commits from maintainers are allowed.
=> Added CI so I can get public docker images

pkg/drivers/dqlite/no_dqlite.go, pkg/drivers/sqlite/sqlite_nocgo.go
This is related to #53 - was turned up by enabling CI builds. 
=> Fix compilation errors with NOCGO

pkg/client/client.go
Signed-off-by: galal-hussein <hussein.galal.ahmed.11@gmail.com>
https://github.com/rancherlabs/rancher-security/issues/501
=> Add Delete function to storage client wrapper

go.mod, go.sum
=> Bump go-sqlite3 to v1.14.8 / sqlite3 v3.36.0

pkg/drivers/generic/generic.go, pkg/drivers/sqlite/sqlite.go, pkg/logstructured/sqllog/sql.go
(cherry picked from commit c1edece7772b4ff4f1f03f01d5218fbfe854c0cc)
=> Call wal_checkpoint during startup/compact for sqlite

pkg/drivers/generic/generic.go
=> listSQL do subquery first then order by - fix #77

pkg/server/kv.go
Signed-off-by: Derek Nola <derek.nola@suse.com>
=> Remove duplicate KeysOnly check

.drone.yml, scripts/build, scripts/version
=> Fix drone publish for arm

pkg/server/delete.go
=> Return a proper ResponseDeleteRange on Delete calls

.drone.yml
Same fix we did everywhere else:
* https://github.com/k3s-io/k3s/pull/6769
* https://github.com/k3s-io/klipper-helm/pull/52
* https://github.com/k3s-io/helm-controller/pull/169
and so on
=> Fix plugins/docker arm tag

.gitignore, Makefile
**Proposed Changes**
* Added a makefile to build the project
* Change the .gitignore to not see .dapper
**Types of Change**
* Development and build environment
**Testing**
**Linked Issues**
=> Adding makefile

.drone.yml
For:
* https://github.com/k3s-io/kine/issues/199
=> fix github-release step for arm

main.go, pkg/drivers/generic/generic.go, pkg/drivers/pgsql/pgsql.go, pkg/logstructured/sqllog/sql.go, pkg/server/types.go
* For https://github.com/k3s-io/k3s/issues/8708
=> Fix issue with gap fill records clobbering inserts under load on pgsql

scripts/test-run-postgres
Commit https://github.com/k3s-io/kine/commit/6d65d058875833e51bd9ff0dfe1269f520aa513a accidentally disabled postgres testing.
Signed-off-by: Derek Nola <derek.nola@suse.com>
=> Actually run postgres tests

.drone.yml
Signed-off-by: Derek Nola <derek.nola@suse.com>
=> Limit testing to pull_requests

.drone.yml
* For https://github.com/k3s-io/kine/issues/248
=> Fix publish step order and dependencies

README.md, docs/flow.md
Adds developer docs on kine internals, including a mermaid flow diagram and bulleted discussion of information flow.
=> Add brain dump on watch flow

pkg/server/server.go
Allows testing kine with grpcurl, and grpc health checking from kubelet
Ref: 
* https://github.com/k3s-io/kine/issues/252
=> Add grpc reflection support

pkg/drivers/mysql/mysql.go
check mysql db and table exist before creating, because mysql user granted select,insert,update,delete on table kine can not create ddl sql in some case.
=> check mysql db and table exist

README.md
* https://github.com/k3s-io/kine/issues/300
=> include MariaDB in README.md

pkg/drivers/sqlite/sqlite.go, pkg/logstructured/sqllog/sql.go
Fixes for:
* https://github.com/k3s-io/kine/issues/357
=> Fix compact transaction
