- pkg/drivers/generic/generic.go
- pkg/drivers/mysql/mysql.go
- pkg/logstructured/logstructured.go
- pkg/logstructured/sqllog/sql.go
- pkg/server/watch.go
This is currently untested, but the idea is to ensure that watch events are always sequential to avoid missing an ID due to an out of order insert.  In such a situation that we see a gap in the log we give up to 1 second to find the missing record.  If it is not discovered in 1 second we move on with the log.
> Attempt to ensure that watch is always sequential

- pkg/server/list.go
Due to checking the wrong variable More is never set to true. This
causes an issue specifically only when k8s does selector based lists
that are also paginated.
> Fix issue in which More is never set

- pkg/drivers/sqlite/sqlite.go
- pkg/drivers/sqlite/sqlite_nocgo.go
Since SQLite depends on the C library and some Golang archs doesn't have CGO support, this PR adds a stub where Kine is generated but without SQlite support.
> Stub-out sqlite drivers to build Kine without CGO

- pkg/client/client.go
- pkg/logstructured/sqllog/sql.go
On list if revision != 0 and startKey != "" it is assumed that startKey exists.  If it doesn't exists nothing will be returned. If we are starting a new list at a revision then startKey will equal prefix and that key does not exists.  This change will set startKey to "" in this situaion so that list works.
> Adjust startKey on list start

- pkg/drivers/sqlite/sqlite_nocgo.go
Fix signature of `sqlite.New` function updated on https://github.com/rancher/kine/commit/c395d22fffc82863dccd39bb807a26bafd107b9d.
> Update function signature on nocgo stub

- pkg/logstructured/sqllog/sql.go
- pkg/server/watch.go
* Send Cancel when server initiates a close
* Don't hold lock over long I/O
* Tie broadcaster channel context to grpc request
> Clean up lock usage

- pkg/drivers/generic/generic.go
- pkg/logstructured/sqllog/sql.go
This fixes the bug that causes a duplication compact_rev_key in HA and also dedups it on start.
> Dedup compact_rev_key on start

- Dockerfile
Such a container could be used as a sidecar container for any k8s api server (such as aggregated APIs).
Contributes to #26.
I picked alpine 3.11 as the base image to try to keep things tiny.
> Add Dockerfile for building Kine in a container image

- main.go
- pkg/drivers/dqlite/dqlite.go
- pkg/drivers/dqlite/no_dqlite.go
- pkg/drivers/generic/generic.go
- pkg/drivers/mysql/mysql.go
- pkg/drivers/pgsql/pgsql.go
- pkg/drivers/sqlite/sqlite.go
- pkg/endpoint/endpoint.go
This PR should solve the constant error messages (as described here: https://github.com/rancher/k3s/issues/1459) when using a small DB instance, e.g. db.t2.micro PostgresQL on AWS, which only can handle up to ~80 connections. This especially happens when listing all pods/workloads of the System project. I think it will just occur at any page which lists a lot of k3s resources.
The error messages also surfaced in the k3s journal logs:
```
ERRO[2020-05-28T10:17:52.444132093Z] error while range on /registry/configmaps/kube-system/cert-manager-cainjector-leader-election-core : pq: sorry, too many clients already
ERRO[2020-05-28T10:17:52.444589524Z] error while range on /registry/configmaps/kube-system/cert-manager-cainjector-leader-election : pq: sorry, too many clients already
E0528 …
```
> Make connection pooling adjustable

- main.go
- pkg/drivers/generic/generic.go
As per https://github.com/rancher/kine/pull/37#issuecomment-665492471
setting this to 0 or allowing it to default to 0 imposes a severe
performance penalty.
> Copy upstream behavior around setting maxIdle to 0

- pkg/drivers/mysql/mysql.go
- pkg/drivers/pgsql/pgsql.go
- pkg/drivers/sqlite/sqlite.go
* Fix issue where compact_rev_key was protected from deletion, instead
of the row it points to. Honestly we should have stored the
compact_rev marker in the value instead of the prev_revision
column. (#61)
Test:
1. Run kine for k3s with external DB: `k3s --debug server --datastore=mysql://X`
1. Wait for compaction message to appear in log output - something like `level=debug msg="COMPACT deleted 0 rows from 3 revisions in 2.484763ms - compacted to 3/1745"`
1. Stop k3s+kine
1. Run query: `SELECT id, name FROM kine WHERE name = "/registry/health";`
1. Run query: `UPDATE kine SET prev_revision = 1 WHERE name = 'compact_rev_key';` - use the ID from the previous step instead of `1` if it was different.
1. Start k3s; wait for compaction message to appear in log output
1. Run query: `SELECT id, …
> Fix bad check in compact query

- scripts/build
Disabling CGO (and sqlite support along with it) wasn't intentional. The build script was copy-pasted from go-skel as per https://github.com/k3s-io/kine/issues/26#issuecomment-586618919 and https://github.com/k3s-io/kine/pull/42.
Fixes #68
> Enable CGO for sqlite support in docker images

- Dockerfile.test.dapper
- pkg/client/client.go
- pkg/logstructured/sqllog/sql.go
* Ensure that initial compaction runs during Start. Deferring this until
Watch creates a race condition wherein we can start answering
requests before compact_rev_key is created, which will cause SQL errors
as seen in k3s-io/k3s#3523.
* Fix client.Delete; the current implementation does not actually work
because delete is only implemented within transactions.
* Fix CI tests by pinning the library we're using to output perf stats
> Ensure compaction runs during startup

- go.mod
- go.sum
> [release-0.6] Bump go-sqlite3 to v1.14.8 / sqlite3 v3.36.0

- go.mod
- main.go
- pkg/drivers/generic/generic.go
- pkg/drivers/generic/tx.go
- pkg/drivers/mysql/mysql.go
- pkg/drivers/pgsql/pgsql.go
- pkg/drivers/sqlite/sqlite.go
- pkg/endpoint/endpoint.go
- pkg/endpoint/http.go
- pkg/logstructured/logstructured.go
- pkg/logstructured/sqllog/sql.go
- pkg/server/cluster.go
- pkg/server/dbsize.go
- pkg/server/kv.go
- pkg/server/lease.go
- pkg/server/limited.go
- pkg/server/maintenance.go
- pkg/server/server.go
- pkg/server/types.go
- pkg/server/watch.go
- pkg/version/version.go
- scripts/build
In upstream etcd, the version endpoint is implemented as a simple JSON handler, muxed with the GRPC server on the client port. This PR implements the required muxing for both plaintext and TLS listeners, using an approach inspired by upstream etcd. Kine now sends a hardcoded etcd version response that should satisfy clients such as kubeadm's [preflight checks](https://github.com/kubernetes/kubernetes/blob/release-1.21/cmd/kubeadm/app/preflight/checks.go#L694) (fixing #30).
This PR also splits the server code into different files per GRPC service, and adds a Cluster service that only supports GetMembers. The service returns a fixed member list that uses the GRPC ":authority" metadata (analogous to the HTTP Host header) to set the returned peer and client URLs. This should be sufficient to …
> Add support for etcd version, memberList, and status queries

- pkg/drivers/generic/generic.go
- pkg/drivers/sqlite/sqlite.go
- pkg/logstructured/sqllog/sql.go
- pkg/server/types.go
This should address https://github.com/k3s-io/k3s/issues/3660
As discussed at https://github.com/k3s-io/k3s/issues/4044#issuecomment-928322661, highly active clusters can cause checkpoint starvation due to there always being an active reader. Forcing a checkpoint at the end of compaction should prevent this from occurring, at the cost of blocking writers for a short period. This should not be any worse than the blocking that currently occurs for the compact transaction.
This also adds a WAL truncate at startup, which should shrink the on-disk WAL back down to a reasonable size for users whose files have grown out of control due to the issue described above.
https://sqlite.org/pragma.html#pragma_wal_checkpoint
> Call wal_checkpoint during startup/compact for sqlite

- go.mod
- main.go
- pkg/drivers/dqlite/dqlite.go
- pkg/drivers/dqlite/no_dqlite.go
- pkg/drivers/generic/generic.go
- pkg/drivers/generic/tx.go
- pkg/drivers/mysql/mysql.go
- pkg/drivers/pgsql/pgsql.go
- pkg/drivers/sqlite/sqlite.go
- pkg/drivers/sqlite/sqlite_nocgo.go
- pkg/endpoint/endpoint.go
- pkg/logstructured/sqllog/sql.go
- pkg/metrics/metrics.go
- pkg/metrics/registry.go
- pkg/metrics/server.go
- pkg/util/string.go
This PR introduce metrics to kine.
It'll expose below metrics:
* SQL Total & Errors: Counter metrics which hold the total number of SQL operations and failed SQL operations. This is helpful for quickly tracking and alerting local SQL errors which have a variant of causes (network, db, etc.) thus not easy to monitor.
* SQL Time: Histogram metric which keeps track of the duration of SQL operations. This duration is measured locally and can be used as a supplement to the SQL exec time measurement of db.
* Compact Errors: Counter metrics which hold the total number of compact errors. Helpful for alerting when continuous compact errors occur which can lead to uncontrollable growth of db size.
* [DBStats metrics](https://github.com/prometheus/client_golang/pull/866) of sql.DB used by kine.
* …
> Introduce metrics

- pkg/drivers/jetstream/jetstream.go
- pkg/logstructured/logstructured.go
- pkg/server/get.go
- pkg/server/types.go
Related to: https://github.com/rancher/rancher/issues/36922
Caused by: https://github.com/kubernetes/kubernetes/pull/108569
Get requests with a field-selector now create range requests that include a limit (page size) that is managed by the apiserver. Kine was enforcing an unconditional restriction on the limit not being set, when the apparent intention was to only prohibit use of limit + rangeEnd at the same time.
Kubernetes 1.24 will when searching within a namespace for a resource using FieldSelector on metatada.name, send a Get request for the fully qualified resource name, but with a non-zero limit:
`RangeRequest Key=/registry/services/specs/default/kubernetes RangeEnd= Limit=500 Revision=0 SortOrder=0 SortTarget=0 Serializable=false KeysOnly=false CountOnly=false`
Confirmed that …
> Only enforce RangeEnd + Limit restriction when RangeEnd is set

- pkg/drivers/mysql/mysql.go
> MySQL [xxx]> CREATE UNIQUE INDEX kine_name_prev_revision_uindex ON kine (name, prev_revision);
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
creating index will failing on mysql prior to 5.6 version, explicitly using ascii charset will workaround the failure
https://stackoverflow.com/a/1814594
> Explicitly use ascii charset for the name column 

- go.mod
- go.sum
Bump go-sqlite3 to v1.14.15 / sqlite3 v3.39.2
> Bump go-sqlite3 to v1.14.15 / sqlite3 v3.39.2

- main.go
- pkg/metrics/server.go
This PR adds a new flag, which, when enabled, allows for remote profiling using `net/http/pprof` package, with the handlers mounted to the metrics server.
By default the flag is disabled, to ensure that the change is backwards-compatible.
This allows for ad-hoc and continuous (e.g. using https://pyroscope.io/) profiling, which is useful for finding memory / cpu bottlenecks.
> Add ability to enable remote profiling using pprof

- go.mod
- go.sum
- pkg/drivers/jetstream/jetstream.go
- pkg/drivers/jetstream/kv/kv.go
- scripts/test-run-jetstream
- Bumps the nats clinet to ~v1.17.0~ `v1.17.1-0.20220923204156-36d2b654c70f`
- Fixes the `DbSize` function to call Stream Info in order to get the stream size
> Bump nats client to v1.17.1-0.20220923

- pkg/server/delete.go
Follow-up PR for #145 to account for delete operations that do not succeed.
For more context see:
- https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L337-L338
- Slack discussion with sig-api-machinery https://kubernetes.slack.com/archives/C0EG7JC6T/p1668796684479099. The decision is that it's up to the etcd3 implementation to return a valid response, and on failed deletes this means return a `ResponseRange` instead (as it falls-through to a simple get response).
@brandond Apologies for the initial PR being incomplete, I'm testing this as I go as well :) With this change I don't see anything blowing up, so things should be fine now.
> Failed delete must return a ResponseRange instead

- pkg/logstructured/sqllog/sql.go
These messages are important for evaluating cluster heath and should be more visible.
> Increase COMPACT log messages to Info

- examples/minimal.md
The main Kubernetes container registry is now defaulted to registry.k8s.io. See: https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/.
Switching to the new registry in the using with kubeadm sample.
>  switch to registry.k8s.io

- updatecli/updatecli.d/updatecli.yml
This resolves an error where updatecli trims some of the version information from the validation target.
> Remove updatecli tranformers

- Dockerfile.dapper
- Dockerfile.test.dapper
- scripts/test-helpers
This PR does:
1. Bump Golang and Alpine image versions to `golang:1.20-alpine3.17` following PR https://github.com/k3s-io/kine/pull/164.
2. Fixes a CI script failure (see [failed pipeline](https://drone-pr.k3s.io/k3s-io/kine/190/1/3)) due to an update to Busybox's version. Part of the fix comes from https://github.com/k3s-io/k3s/pull/6744.
1. This fix requires to add the package `findutils` to `Dockerfile.test.dapper` in order for `find` to support `printf`).
1. Re-ordered alphabetically the packages installed by `apk`.
2. Also re-ordered the parameters ` -mindepth 2 -maxdepth 2 -type d` to make them work as expected and avoid failure:
```shell
find: warning: you have specified the global option -mindepth after the argument -type, but global options are not positional, i.e., -mindepth …
```
> Golang and Alpine image bumps

- Dockerfile.dapper
This will use the golangci-lint installer that is on the master branch, per their [installation guide](https://golangci-lint.run/usage/install/). This will always install the latest golangci-lint version.
> install golangci-lint from master

- Dockerfile.dapper
This enables the use of go proxy and module cache for the goimports install by installing the commit hash at HEAD where the tag is. If we install from the commit hash we no longer need to bypass the proxy and we will benefit from the extra resilience. 
The earlier trade-off was the intent to keep things easier to update by using a human identifiable tag name and lose the benefits of the go proxy and module cache. I am generating automation which will keep the version up to date more easily, so I want to resolve the go proxy issue. I want this to resolve first to avoid duplicate effort as I need to update automation to keep the hash up to date after this change.
For human readability I am adding a comment with the corresponding tag version, this allows humans to easily validate the …
> Install goimports from commit hash instead of tag

- updatecli/updatecli.d/updatecli.yml
- updatecli/values.yaml
While updating files I realized that having the repo information in the values file was going to cause synchronization issues.
This resolves this, expecting new configs to contain the owner and names of the repos they need.
> Remove repo info from global scope

- updatecli/updatecli.d/dockerfile_dapper_goimports.yml
This add a config to get the latest goimports release, update the tag name in the comment and update the commit hash in the go get line of the Dockerfile.
> Add goimports config

- pkg/drivers/nats/nats.go
- pkg/endpoint/endpoint.go
Existing deployments using this scheme will effectively ignore the embedded server options.
/cc @brandond
> Revert legacy behavior for jetstream:// scheme

- examples/minimal.md
> Fix typo (k3s -> kine) in minimal.md

- pkg/logstructured/sqllog/sql.go
Because it will cause memory leak if we do not stop ticker when the function has completed.
> Fix SQLLog.compactor

- pkg/drivers/sqlite/sqlite.go
Under stress, concurrent operations (notably while garbage collection is in progress) can result in failed calls with error SQLITE_BUSY (database is locked).
The SQLITE_BUSY result code is an expected outcome when the database file could not be written (or in some cases read) because of concurrent activity: https://www.sqlite.org/rescode.html
SQLite ships a busy timeout retry mechanism as a PRAGMA (https://www.sqlite.org/pragma.html#pragma_busy_timeout), that can be set via go-sqlite3's connection string.
That makes go-sqlite3 retry operations that fail with SQLITE_BUSY transparently to users.
Fixes https://github.com/k3s-io/k3s/issues/8234
> SQLite: specify a busy timeout

- pkg/server/delete.go
- pkg/server/kv.go
- pkg/server/limited.go
- pkg/server/types.go
- pkg/server/update.go
Add check for mod revision=0 in update txn
Also, return proper GPRC errors to improve client handling.
* For https://github.com/k3s-io/kine/issues/228
> Add check for mod revision=0 in update txn

- pkg/logstructured/logstructured.go
- pkg/logstructured/sqllog/sql.go
- pkg/server/get.go
- pkg/server/types.go
Always send ErrCompacted when getting/listing compacted revisions; ignoring it for get by revision is not correct.
Always send ErrFutureRev when getting/listing future revisions; pretending that the requested revision is the current revision is not correct.
* For https://github.com/k3s-io/kine/issues/215
> Properly return ErrCompacted/ErrFutureRev for get/list

- .drone.yml
- .github/workflows/unit.yml
- Dockerfile.test
- hack/histogram.py
- hack/loadmap.py
- scripts/test
- scripts/test-helpers
- scripts/test-run-postgres
- Drone now deploys seperate DB testing that runs in parallel.
- Slightly reduced test load from 5K to 4K, this combined above brings total time down to around ~11 minutes (vs 45-50 before).
- Converted unit test check to github actions as no building of kine is required. Also we currently lack an unit tests, however several upcoming PRs have added some.
- Dropped oldest Postgress 11.X, it goes EOL next week.
Signed-off-by: Derek Nola <derek.nola@suse.com>
> Parallelize Drone testing

- go.mod
- go.sum
- pkg/logstructured/logstructured.go
Hi @brandond 
Since there are many commits that need to be rebased and in order to make the pr cleaner, I re-submitted this change based on the master branch.
Please help to have a review, Thanks.
Related Issue or pull request: 
* #221 [Would be closed when this pr is merged] 
* #219 
* #47
> refactor: update ttl event expiry model

- pkg/drivers/nats/nats.go
- pkg/logstructured/logstructured.go
- pkg/logstructured/sqllog/sql.go
- pkg/server/list.go
- pkg/server/types.go
- pkg/server/watch.go
* Fixes an error where watching a compacted revision would return events, followed by an error. The watch is now immediately cancelled with an appropriate error, and the compact/current revision fields set.
* Fixes an error where a high event rate could flood the GRPC stream with single-event watch responses. The event channel reader now merges all available events, and sends them in a single watch message. This was most frequently an issue on sqlite, where all inserts are done locally and immediately wake the polling goroutine to send the event without any opportunity for batching.
Fixes pod watch events being dropped when using kine to reproduce the issue described at https://github.com/kubernetes/kubernetes/issues/121688 
Ref: SURE-6953
> Fix multiple issues with Watch

- pkg/drivers/pgsql/pgsql.go
With the current master branch code
(commit afb2121bb0d8c2e079f90f7d3a1b1a2c3338bfa1)
I see the following error:
root@vm2:/home/vagrant# kine --debug --endpoint postgres://postgres:postgresql@localhost:5432/foobster INFO[2023-11-03T20:07:09.379099258Z] metrics server is starting to listen at :8080 INFO[2023-11-03T20:07:09.379709686Z] starting metrics server path /metrics FATA[2023-11-03T20:07:09.40247106Z] building kine: failed to connect to `host=localhost user=postgres database=foobster`: server error (FATAL: database "foobster" does not exist (SQLSTATE 3D000))
This is fixed with the current commit.
> Bugfix? create pgql database if not exists

- pkg/drivers/nats/backend.go
- pkg/drivers/nats/logger.go
- pkg/logstructured/logstructured.go
- pkg/server/types.go
- pkg/server/watch.go
Up until now this option was silently ignored, possibly resulting in incorrect behavior if used by clients
For: 
* https://github.com/k3s-io/kine/issues/250
> Add ProgressNotify support

- pkg/drivers/pgsql/pgsql.go
The database might already exist even if we encounter errors in createDBIfNotExist, so instead of erroring out, log warnings and attempt to continue.
Fixes https://github.com/k3s-io/k3s/issues/9033
> Attempt to continue when encountering errors in createDBIfNotExist

- go.mod
- main.go
- pkg/endpoint/endpoint.go
- pkg/logstructured/sqllog/sql.go
- pkg/server/limited.go
- pkg/server/server.go
- pkg/server/watch.go
* Adds support for watch progress requests.
If all channels are synced, sends the current revision using channel -1. This allows the watch client to determine the datastore's current revision on-demand in between progress report intervals.
This matches the implementation from upstream etcd: 
* https://github.com/etcd-io/etcd/blob/v3.5.11/server/mvcc/watchable_store.go#L485-L487
* https://github.com/etcd-io/etcd/blob/v3.5.11/server/mvcc/watchable_store.go#L500-L504
For:
* https://github.com/k3s-io/kine/issues/267
* Make progress report notification interval configurable.
Required by kubernetes as per https://github.com/kubernetes/kubernetes/issues/122805#issuecomment-1898386268
* Optimize CurrentRevision checks by sharing current revision marker from poll loop
Progress notifications query …
> Add support for WatchProgressRequest

- examples/Dockerfile
- examples/generate-certs.sh
- examples/minimal.md
- examples/mysql-ssl.cnf
- examples/server_openssl.cnf
*  Changes for the minimal docs
* A better automation when creating a minimal kine environment for testing
> Update for minimal setup

- pkg/endpoint/endpoint.go
- Returns the config that will be used in the client in k3s in case we use tls
> Add a return when kine is set to use tls

- .drone.yml
- pkg/drivers/mysql/mysql.go
- pkg/drivers/pgsql/pgsql.go
- scripts/test
- scripts/test-helpers
- scripts/test-run-schema-migration
Extends id column to bigint for new databases.
Existing databases will be migrated if the KINE_SCHEMA_MIGRATION environment variable is set to 1 or higher.
> Update schema and add migrations for mysql and pgsql

- pkg/logstructured/logstructured.go
- This error log appear when k3s closes the first kine client after the bootstrap when using tls, so we do not need the log at this moment.
> Add a if to not send logs when context is canceled

- pkg/logstructured/sqllog/sql.go
- When testing kine with k3s/rke2 I discovered that this log appears sometimes when the context is canceled quickly
> Add a error verification when failed list is from context canceled

- pkg/client/client.go
- pkg/drivers/nats/backend.go
- pkg/drivers/nats/logger.go
- pkg/logstructured/logstructured.go
- pkg/logstructured/sqllog/sql.go
- pkg/server/compact.go
- pkg/server/create.go
- pkg/server/kv.go
- pkg/server/limited.go
- pkg/server/types.go
This PR adds support for gRPC compaction requests for all backends. For NATS, compaction is handled by Jetstream and the bucket's `History` setting, so compaction requests are no-ops.
Additionally, unused params were removed from the LimitedServer's `compact` and `create` methods.
Given that the default compaction interval of 5min is not exposed as a configuration option, it can be useful to be able to trigger ad hoc compactions, which partially addresses #230.
```golang
package main
import (
"context"
"fmt"
"os"
"strconv"
"go.etcd.io/etcd/etcdserver/etcdserverpb"
"google.golang.org/grpc"
"google.golang.org/grpc/credentials/insecure"
)
func main() {
compactRevision := os.Args[1]
cr, err := strconv.ParseInt(compactRevision, 10, 64)
if err != nil {
panic(err)
}
conn, err := …
```
> feat: compaction support

- pkg/metrics/metrics.go
This corrects https://github.com/k3s-io/kine/issues/305 by only dumping the sql query parameters in the slow sql log if the log level is set to trace.
> fix: only log slow sql query parameters if trace logging is enabled

- pkg/logstructured/logstructured.go
Fixes issue where the TTL watch would attempt to start with a compacted revision, if the initial list of non-deleted keys contained only entries that had been compacted.
The watch should start with the current revision, not the max undeleted revision.
* ref:  https://github.com/k3s-io/kine/issues/311
> Start TTL watch at current revision, not max KV revision

- main.go
- pkg/drivers/nats/new.go
- pkg/endpoint/endpoint.go
- pkg/server/maintenance.go
- pkg/server/server.go
Fixes #315 
See https://github.com/kubernetes/kubernetes/blob/beb696c2c9467dbc44cbaf35c5a4a3daf0321db3/staging/src/k8s.io/apiserver/pkg/storage/feature/feature_support_checker.go#L157
Which expects that the etcd status endpoint return a version. This returns a default version allowing users to override it if necessary.
> Return an emulated etcd version in the status endpoint

- main.go
- pkg/tls/config.go
As mentioned here: https://github.com/k3s-io/k3s/issues/1093 , it is not possible to skip TLS verification. This patch adds support for skipping it. Not sure if it's the correct approach tho :)
> Add support for TLS skip verification

- pkg/drivers/mysql/mysql.go
- pkg/drivers/pgsql/pgsql.go
Co-Authored by @adriangonz who paired with me on this change and also tested/benched all the changes 🎉 
This builds on top of the great work done in #151 by @moio (included as a co-author on this PR since it builds on top of the ideas introduced in the said PR)
Individually we were able to bring the count query down to 1.5s from ~40s and the list query down to 0.5s from ~30s on our test bench.
This is fairly significant as it makes kine usable/scalable at such high volume of objects.
Without the above changes we would usually see timeouts and context cancelled errors most of the times.
In Postgres, `text` tends to give better performance and use less space. When using `varchar`,
- Values get padded to the max size (whereas `text` values can be sparse).
- Each update / insert has an extra …
> Dramatically improve postgresql performance

- .github/dependabot.yml
This change allows Dependabot to automatically check for updates to Go module dependencies and create pull requests for those updates.
> ci: add gomod to dependabot

- .github/dependabot.yml
Group etcd and k8s bumps together to reduce PR spam. Have dependabot ignore NATs bumps as those require manual review and implementation by the NATs contributors.
> Dependabot: Group common go dependencies, ignore NATS

- pkg/logstructured/sqllog/sql.go
Fixes https://github.com/k3s-io/kine/issues/363
Undo the change from #360 and fix things the right way. That worked, but had the unfortunate side effect of moving the compact target forward within the inner loop. This whole thing can be done better by simplifying the error handling.
* Revert "Record compact progress and metrics per iteration"
This reverts commit aa4f2a7c621b64aba27c6b1298c0481e0c0018bf.
* Simplify compact loop error handling
Rather than restarting the outer loop on unhandled error, simmply break out of the inner loop on any error. We always want to update the compact and target rev, and do post-compact operations - so the only thing we really need to check the error for is logging and metrics.
> Fix rolling compact

- pkg/drivers/generic/generic.go
- pkg/drivers/mysql/mysql.go
- pkg/server/types.go
One problem we encountered when using Kine with the MySQL driver is that it uses an unexpected high amount of database connections, even after setting the flag `--datastore-max-open-connections` to a small number. 
We investigated and found out that during the `createDBIfNotExist` function two database connections are created as well that are never closed. For the PostgreSQL driver the connection is closed as expected:
https://github.com/k3s-io/kine/blob/133503d8acbf5979279e32b5a1ff28882c70212a/pkg/drivers/pgsql/pgsql.go#L223
For the MySQL driver, these close after creation defers are missing and hence the connections stay open all the time. This PR adds two lines to close the database connections as expected after making sure the database exists in the MySQL server.
EDIT: Not sure why …
> fix: close mysql connection after create database

- pkg/logstructured/logstructured.go
- pkg/server/types.go
- pkg/server/watch.go
Anytime the server attempts to cancel a watch request, it should set the `canceled` field to true, regardless of whether `err` is empty or not. Let `err` only affect the `reason` field.
> fix: canceled should always be set to true when cancel a watch request

- Dockerfile
- scripts/test-run-cockroachdb
- scripts/test-run-mysql
- scripts/test-run-nats
- scripts/test-run-postgres
- Update all the various DB we test, remove EOL versions.
- Reduce number of cockroachdb versions tested from 3 to 2. This DB takes significantly longer than other DBs to test.
> Update all testing DBs, remove EOL versions

- pkg/logstructured/logstructured.go
Follow-up to the discussion at https://github.com/k3s-io/kine/issues/382#issuecomment-2544567245
handleTTLEvents already calls loadTTLEventKV which gets the most recent event for the key while holding a lock. This is then checked to confirm expiration before calling deleteTTLEvent.
Because it's checked before calling, we don't need to do a locked check of the store AGAIN in deleteTTLEvent. If another goroutine updated the key in the time between when loadTTLEventKV returned the event, and the time that deleteTTLEvent tries to delete it, the actual Delete will fail because the modRevision is no longer current, and the error path will ensure that the key is re-enqueued and processed at the correct time.
> Drop unnecessary expire time check in ttl event handler

- pkg/server/kv.go
In my perspective context cancellation is not an error event, it is business as usual. WDYT?
> Do not log context cancelled as error

- .github/workflows/unit.yml
- pkg/drivers/sqlite/sqlite_nocgo.go
- pkg/endpoint/endpoint.go
This was broken during review-based refactoring in
* https://github.com/k3s-io/kine/pull/325
We generally don't build with cgo disabled so this wasn't noticed.
> Fix builds with CGO_ENABLED=0

- scripts/build
I do not fully understand how the Dapper scripts work, but build works, so should be good?
How I tested it:
```sh
make ARCH=riscv64
docker run \
--rm --interactive --tty \
--volume=./bin/:/mnt/bin \
--platform=linux/riscv64 \
riscv64/busybox \
/mnt/bin/kine
```
Closes #296
> feat: support RISC-V 64

- pkg/logstructured/sqllog/sql.go
We encountered issues with our setup after updating Kine to version v0.13.7. The issues we encountered where similar to the ones described in #357 and were supposed to be fixed in #360 and #365.
While I noticed that our custom SQLite DSN was missing a few options that seem to help remedy the issues, I still had the impression something else was not playing nice as well.
So after building a local test setup and using the `jobloader` example to create a small load generator that matched our usage profile (guess in hindsight that wasn't even necessary) I was able to reproduce the issue.
We noticed in the test logs that at a certain moment in time the compaction process stopped all together, just as it does in our production setup. Before it stopped it already failed a few times (each time …
> fix: only update revisions if currentRev is updated

- go.mod
- pkg/server/watch.go
- pkg/util/wait.go
Also has the additional benefit of removing 1 of the K8s direct dependencies.
> Remove direct use of deprecated `wait` function

- pkg/drivers/nats/config.go
- pkg/drivers/pgsql/pgsql.go
- pkg/util/url.go
Resolves #411 
Wrap parse errors with a hint: `error parsing URL. Ensure that any embedded values such as username & password have been URL encoded: <wrapped error>`
> return url encoding hint with url parse error

- README.md
This is standard markdown syntax. Removes the '=====...' in markdown viewers (github etc.)
> Fix markdown to use equals as header.

- Dockerfile
Latest version of golangci-lint is not compatible with previous version of configuration. In long term would be nice to migrate the configuration, but for quick fix the build can install previous version.
> Install golangci-lint version 1 to fix validation

- .github/workflows/release.yml
- Dockerfile
- Makefile
- scripts/buildx
- Fix releases to properly include CGO build of the binaries
- Readds riscv64 builds
> Use tonistiigi/xx to enable CGO multiplatform builds

- .drone.yml
- .github/workflows/pr.yml
- Add CI that checks builds on PR. This covers all 4 platforms we build (armv7, arm64, amd64, riscv64). Ensures dependabot PRs also get some validation.
- Remove Drone arm32 and arm64 CI, no longer used/needed.
> Remove arm32/64 Drone CI, add PR build checks in GHA

- .github/dependabot.yml
We don't update k8s dependencies to a new minor comes out every 3 months. Checking every week just cause PR spam.
> Reduce k8s dependabot checks to monthly.

- .github/dependabot.yml
https://github.com/k3s-io/kine/pull/465 Introduced a invalid dependabot config. Unfortunately, this can't be caught in PR due to [how dependabot permissions work.](https://github.com/dependabot/dependabot-core/issues/4605). 
This fixes the configuration and allows for two different `gomod` schedules.
> Fix dependabot config for gomod

- pkg/app/app.go
- pkg/drivers/config.go
- pkg/drivers/generic/generic.go
- pkg/drivers/mysql/mysql.go
- pkg/drivers/pgsql/pgsql.go
- pkg/drivers/sqlite/sqlite.go
- pkg/endpoint/endpoint.go
- pkg/logstructured/sqllog/sql.go
- pkg/metrics/metrics.go
Hi! I'm pushing upstream some of our changes. All of the changes have been tested in our clusters and are backwards compatible.
1. The compact operation configuration is now exposed via CLI flags: `--compact-timeout`, `--compact-min-retain`, `--compact-batch-size`, and `--poll-batch-size`. We run quite a few clusters and wanted an easier way to tune these settings to optimize our database load. Default values and behavior haven't changed.
2. Added the flag `--metrics-ignore-tls-config`, which, if set to `true`, will expose the `/metrics` endpoint over HTTP without TLS, regardless of the main endpoint's configuration. Not sure if the naming of the flag is perfect, but it simply prevents copying the TLS config in this line: `metricsConfig.ServerTLSConfig = config.ServerTLSConfig`.
3. Added …
> Configurable compaction and observability enhancements

- pkg/app/app.go
app.Run needs argv[0] set to a command name, not the first flag.
> Fix issue where first arg/flag was ignored when generating config

- .github/workflows/release.yml
- Dockerfile
- Makefile
- scripts/buildx
- scripts/test-helpers
- scripts/version
Linked issue:
* https://github.com/k3s-io/kine/issues/495
`git status` cannot be used because the Dockerfile doesn't copy in all the files from the working directory; as a result git thinks the files have been deleted and the repo is dirty.
> Fix build args for multi-arch-build make target

- scripts/test-conformance
- scripts/test-helpers
Use a newer v1.30 line and the new GHCR published image.
> Update test to use newer ghcr k3s image

- pkg/app/app.go
- pkg/metrics/registry.go
Fixes panic when both etcd and kine are in use.
Ref: https://github.com/k3s-io/k3s/actions/runs/17423032792/job/49465181404?pr=12853
```
panic: duplicate metrics collector registration attempted
goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000884140, {0xc0011c9190?, 0x4?, 0xc0010fd2b0?})
/go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/registry.go:406 +0x65
github.com/k3s-io/kine/pkg/drivers/generic.Open({0x7ffed40, 0xc00063cdc0}, {0x6eeef67, 0x7}, {0x7103501, 0x4d}, {0x0?, 0x0?, 0xc001208340?}, {0x7f4b4a0, ...}, ...)
/go/pkg/mod/github.com/k3s-io/kine@v0.13.17/pkg/drivers/generic/generic.go:197 +0x318
github.com/k3s-io/kine/pkg/drivers/sqlite.NewVariant({0x7ffed40?, 0xc00063cdc0?}, {0x6eeef67?, 0x7?}, 0xc00124d140) …
```
> Do not register core metrics in init

- pkg/drivers/generic/generic.go
- pkg/drivers/generic/tx.go
- pkg/drivers/nats/backend.go
- pkg/drivers/nats/backend_test.go
- pkg/drivers/nats/kv.go
- pkg/drivers/nats/logger.go
- pkg/drivers/pgsql/pgsql.go
- pkg/logstructured/logstructured.go
- pkg/logstructured/sqllog/sql.go
- pkg/server/compact.go
- pkg/server/get.go
- pkg/server/kv.go
- pkg/server/list.go
- pkg/server/types.go
- pkg/server/update.go
- pkg/server/watch.go
* Allow apiserver to watch the compact rev key, by redirecting list/get/watch to the substitute key
The apiserver now watches the compact rev key and prunes caches based on the compact revision.
Ref: https://github.com/kubernetes/kubernetes/pull/132876
This is a follow-up to: **Add support for apiserver-managed compact** https://github.com/k3s-io/kine/commit/6c30f90141376d669405611a29220cde98f35717
In order for the 1.34+ apiserver to work properly, kine should be used with `--compact-interval=0` to let the apiserver manage compaction.
* Add support for `clientv3.WithKeysOnly()` list/get option.
Ref: https://github.com/kubernetes/kubernetes/pull/132355
Kubernetes no longer uses `WithCountOnly()` to count keys under a prefix; it now uses `WithKeysOnly()` to list all keys under a prefix and …
> Update kine for compatibility with kubernetes v1.34

- pkg/app/app.go
- pkg/drivers/factory.go
- pkg/drivers/generic/generic.go
- pkg/drivers/http/http.go
- pkg/drivers/mysql/mysql.go
- pkg/drivers/nats/new.go
- pkg/drivers/pgsql/pgsql.go
- pkg/drivers/registry.go
- pkg/drivers/sqlite/sqlite.go
- pkg/drivers/sqlite/sqlite_nocgo.go
- pkg/endpoint/endpoint.go
Gracefully shuts down the GRPC server and closes databases connections, instead of just terminating.
Shutdown will be immediate if there are no streaming clients; if clients are connected it will wait up to 2 seconds for them to close any active streams before stopping.
```console
brandond@dev01:~/go/src/github.com/k3s-io/kine$ ./bin/kine
INFO[2025-09-13T21:21:40.313257287Z] metrics server is starting to listen at :8080
INFO[2025-09-13T21:21:40.313628548Z] starting metrics server path /metrics
INFO[2025-09-13T21:21:40.313940540Z] Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s
INFO[2025-09-13T21:21:40.314009917Z] Configuring database table schema and indexes, this may take a moment...
INFO[2025-09-13T21:21:40.319117746Z] Database tables …
```
> Add WaitGroup support for graceful shutdown

- .drone.yml
- hack/histogram.py
- hack/loadmap.py
- pkg/drivers/pgsql/pgsql.go
- scripts/test-conformance
- scripts/test-helpers
- scripts/test-load
Using postgresql driver some requests fails with `sql: expected 10 destination arguments in Scan, not 9` at https://github.com/k3s-io/kine/blob/adbb708512a6be82e7f1beaabc618b95f490d820/pkg/logstructured/sqllog/sql.go#L658. As i think the driver doesn't take care on `keysOnly` properly and uses wrong query which contains the values too.
Here is the query used for `keysOnly = true`:
```sql
SELECT
(SELECT MAX(rkv.id) AS id FROM kine AS rkv),
(SELECT MAX(crkv.prev_revision) AS prev_revision FROM kine AS crkv WHERE crkv.name = 'compact_rev_key'),
maxkv.*
FROM (
SELECT DISTINCT ON (name)
kv.id AS theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value
FROM
kine AS kv
WHERE
kv.name LIKE $1 
AND kv.name > $2
ORDER BY kv.name, theid DESC
) AS maxkv
WHERE …
```
> Fix sql: expected 10 destination arguments in Scan, not 9 on postgresql
